// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css-emotion/src/Css.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var MdxDeck = require("mdx-deck");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var CodeSurferHighlighter = require("./CodeSurferHighlighter");

var make = CodeSurferHighlighter.Highlighter;

var Highlighter = {
  make: make
};

function CodeSurfer(Props) {
  var code = Props.code;
  var language = Props.language;
  var highlights = Props.highlights;
  var length = highlights.length + 1 | 0;
  var currentStep = MdxDeck.useSteps(length);
  var noSurfing = currentStep === length || currentStep === 0;
  return React.createElement("div", {
              className: Curry._1(Css.style, /* :: */[
                    Css.height(Css.vh(100)),
                    /* :: */[
                      Css.width(Css.vw(100)),
                      /* :: */[
                        Css.padding(Css.px(30)),
                        /* :: */[
                          Css.backgroundColor(Css.hex("fbfbfb")),
                          /* :: */[
                            Css.fontSize(Css.px(30)),
                            /* :: */[
                              Css.display(/* flex */-1010954439),
                              /* :: */[
                                Css.alignItems(Css.center),
                                /* :: */[
                                  Css.justifyContent(Css.center),
                                  /* [] */0
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ])
            }, React.createElement(make, {
                  code: code,
                  language: language,
                  noSurfing: noSurfing,
                  currentHighlights: Belt_Array.get(highlights, currentStep - 1 | 0)
                }));
}

var make$1 = CodeSurfer;

var $$default = CodeSurfer;

exports.Highlighter = Highlighter;
exports.make = make$1;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* make Not a pure module */
