// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css-emotion/src/Css.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function Paragraph(Props) {
  var children = Props.children;
  return React.createElement("p", {
              className: Curry._1(Css.style, /* :: */[
                    Css.padding(Css.px(30)),
                    /* :: */[
                      Css.textAlign(Css.center),
                      /* [] */0
                    ]
                  ])
            }, children);
}

var make = Paragraph;

var $$default = Paragraph;

exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* Css Not a pure module */
