// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css-emotion/src/Css.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

var wrapper = Curry._1(Css.style, /* :: */[
      Css.width(Css.pct(100)),
      /* :: */[
        Css.height(Css.pct(100)),
        /* :: */[
          Css.display(Css.grid),
          /* :: */[
            Css.gridTemplateColumns(/* :: */[
                  Css.fr(1),
                  /* :: */[
                    Css.fr(1),
                    /* [] */0
                  ]
                ]),
            /* :: */[
              Css.gridColumnGap(Css.px(15)),
              /* :: */[
                Css.alignItems(Css.center),
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]);

var Styles = {
  wrapper: wrapper
};

function SplitLayout(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: wrapper
            }, children);
}

var make = SplitLayout;

var $$default = SplitLayout;

exports.Styles = Styles;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* wrapper Not a pure module */
