// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css-emotion/src/Css.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

var wrapper = Curry._1(Css.style, /* :: */[
      Css.height(Css.pct(100)),
      /* :: */[
        Css.width(Css.pct(100)),
        /* [] */0
      ]
    ]);

var Styles = {
  wrapper: wrapper
};

function VideoBackground(Props) {
  var src = Props.src;
  return React.createElement("video", {
              className: wrapper,
              autoPlay: true,
              loop: true,
              muted: true
            }, React.createElement("source", {
                  src: src,
                  type: "video/mp4"
                }));
}

var make = VideoBackground;

var $$default = VideoBackground;

exports.Styles = Styles;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* wrapper Not a pure module */
