// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

var MyScope = {
  a: 12
};

var myArray = [
  12,
  2,
  4,
  5
];

function MyListMake(Config) {
  var App$MyListMake = function (Props) {
    var data = Props.data;
    var render = Props.render;
    return React.createElement("ul", undefined, Belt_Array.map(data, (function (element) {
                      return React.createElement("li", undefined, Curry._1(render, element));
                    })));
  };
  return {
          make: App$MyListMake
        };
}

var MyListStringConfig = {};

function App$MyListMake(Props) {
  var data = Props.data;
  var render = Props.render;
  return React.createElement("ul", undefined, Belt_Array.map(data, (function (element) {
                    return React.createElement("li", undefined, Curry._1(render, element));
                  })));
}

var MyListString = {
  make: App$MyListMake
};

var MyListIntConfig = {};

function App$MyListMake$1(Props) {
  var data = Props.data;
  var render = Props.render;
  return React.createElement("ul", undefined, Belt_Array.map(data, (function (element) {
                    return React.createElement("li", undefined, Curry._1(render, element));
                  })));
}

var MyListInt = {
  make: App$MyListMake$1
};

function App(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement(App$MyListMake, {
                  data: [
                    "12",
                    "12",
                    "3990"
                  ],
                  render: (function (element) {
                      return React.createElement("div", undefined, element);
                    })
                }), React.createElement(App$MyListMake$1, {
                  data: [
                    12,
                    12,
                    3990
                  ],
                  render: (function (element) {
                      return React.createElement("div", undefined, String(element));
                    })
                }));
}

var a = 12;

var b = "12";

var c = /* "c" */99;

var name = "hey";

var nameNo;

var ab = 12;

var person = {
  name: "adf",
  age: 12
};

var myList = {
  hd: 1,
  tl: {
    hd: 2,
    tl: {
      hd: 4,
      tl: {
        hd: 5,
        tl: /* [] */0
      }
    }
  }
};

var gabriel = /* Admin */0;

var maria = /* admin */474655887;

var myNull = null;

var myUndefined;

var make = App;

exports.a = a;
exports.b = b;
exports.c = c;
exports.name = name;
exports.nameNo = nameNo;
exports.ab = ab;
exports.MyScope = MyScope;
exports.person = person;
exports.myList = myList;
exports.myArray = myArray;
exports.gabriel = gabriel;
exports.maria = maria;
exports.myNull = myNull;
exports.myUndefined = myUndefined;
exports.MyListMake = MyListMake;
exports.MyListStringConfig = MyListStringConfig;
exports.MyListString = MyListString;
exports.MyListIntConfig = MyListIntConfig;
exports.MyListInt = MyListInt;
exports.make = make;
/* react Not a pure module */
