// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var $$Promise = require("reason-promise/src/js/promise.js");

function getNiceNumber(param) {
  var match = $$Promise.pending(undefined);
  var resolve = match[1];
  setTimeout((function (param) {
          return Curry._1(resolve, {
                      TAG: /* Ok */0,
                      _0: 12
                    });
        }), 1200);
  return match[0];
}

function mapToJs(res) {
  if (res.TAG) {
    return ;
  } else {
    return {
            ok: res._0
          };
  }
}

function getNiceNumberJs(param) {
  return $$Promise.map(getNiceNumber(undefined), mapToJs);
}

exports.getNiceNumber = getNiceNumber;
exports.mapToJs = mapToJs;
exports.getNiceNumberJs = getNiceNumberJs;
/* Promise Not a pure module */
