// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function App(Props) {
  var name = Props.name;
  return React.createElement("p", undefined, "Helloooo! " + name);
}

var make = App;

var $$default = App;

exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
