// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var App = require("./App.bs.js");
var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");

ReactDOMRe.renderToElementWithId(React.createElement(App.make, {
          name: "Gabriel"
        }), "root");

/*  Not a pure module */
