// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function makeAwesome(msg) {
  return /* Awesome */{
          _0: msg
        };
}

function Awesome(Props) {
  var mode = Props.mode;
  var match = React.useState(function () {
        
      });
  var setState = match[1];
  var state = match[0];
  return React.createElement("div", undefined, React.createElement("button", {
                  onClick: (function (param) {
                      if (!mode) {
                        return Curry._1(setState, (function (param) {
                                      return "Light is on";
                                    }));
                      }
                      var msg = mode._0;
                      return Curry._1(setState, (function (param) {
                                    return msg;
                                  }));
                    })
                }, "Click for the awesomeness"), state !== undefined ? React.createElement("p", undefined, state) : null);
}

var light = /* Light */0;

var make = Awesome;

var $$default = Awesome;

exports.light = light;
exports.makeAwesome = makeAwesome;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
